### ISSUE TITLE
Call to undefined method stdClass::getBody()

### ISSUE THREAD

**Issue by doofy** [robvankeilegom/firefly-III-paypal-importer#13]
Fresh v0.3.0 with sqlite.

```
$ docker-compose exec paypal php artisan sync
Start pulling data from PayPal

In PayPal.php line 62:
                                                
  Call to undefined method stdClass::getBody()  
```

**Comment by doofy** [comment]
I changed something but I do not know what but it seems to work now. My suspicion is that paypal is very slow with first setup of developer access.

**Comment by RoiArthurB** [comment]
In case someone falls here and doesn't know if it's true, I can confirm that while installing paypal importer and creating API credentials at the same time, I got this error. But after waiting (i.e letting my cron run after some hours), it just worked fine :shrug: 

So be patient and let the automatization work for you all guys ;)
