### ISSUE TITLE
Unprocessable Content

### ISSUE THREAD

**Issue by TransferBradley** [robvankeilegom/firefly-III-paypal-importer#18]
When Pushing the PayPal data to FireFly I get the following errormessage:

Client error: `POST http://192.168.178.10:8082/api/v1/transactions` resulte
d in a `422 Unprocessable Content` response:
{"message":"The transactions.0.description may not be greater than 1000 cha
racters.","errors":{"transactions.0.descripti (truncated...) 

I got this error on my first import as well, But it still imported all/most of the transactions.

It seems however that it is now stuck since I am unable to get my latest transaction into FireFly.
I did verify that the transaction is accesible through the PayPal API

Are descriptions longer than 1000 characters truncated and still processed or is it really an error and is it stuck?

**Comment by shrippen** [comment]
I am getting the same error.
I also have a weird behaviour where most of the transactions are linked to "Cash Account" and not to an actual account name. I am noting this here because it might be related?

**Comment by robvankeilegom** [comment]
@TransferBradley This was fixed in `0.3.3` and `latest`. All descriptions are now truncate to 1000 characters. You can still find the complete text in the note field on the transactions.

**Comment by robvankeilegom** [comment]
@shrippen Do you mean as source account or as destination account?

**Comment by shrippen** [comment]
As the destination account. I am testing this right now with the new 0.3.3 but same behaviour. So it is not related to this issue. Will create a new issue for that.
