### ISSUE TITLE
Crashes when pushing data to Firefly

### ISSUE THREAD

**Issue by zdaar** [robvankeilegom/firefly-III-paypal-importer#6]
Hi, I have the following error when the tool tries to push data to Firefly :

```
Start pulling data from PayPal
Pushing data to Firefly

In Firefly.php line 83:

  Undefined property: stdClass::$errors
```

Could you help ?
Could it be a parsing error or is it my configuration ?
Thanks in advance :)

**Comment by robvankeilegom** [comment]
Hi,

It looks like the application is getting a response it isn't expecting. Check your firefly configuration. 
The PayPal step was completed so you can just run `php artisan sync:firefly`instead of `php artisan sync`. 

I'll add some more error handling and a clearer error message later.

**Comment by robvankeilegom** [comment]
@zdaar Is your problem solved?

**Comment by zdaar** [comment]
@robvankeilegom 
Hi, I went digging around one evening and ended up just comment it out the exception and it seems to have imported fine from there 

                    //$error    = Arr::get(current($response->errors), 0);

                    //if ('This account name is already in use.' === $response->errors->name[0]) {
                   // if ('This account name is already in use.' === $error {

                        $fireflyId = $this->findAccountByName($payer->name);
                    //}
                }
