### ISSUE TITLE
Error on account creation when pushing to Firefly

### ISSUE THREAD

**Issue by flifloo** [robvankeilegom/firefly-III-paypal-importer#7]
When sync to Firefly, I got this error:
```
Pushing data to Firefly

In Firefly.php line 198:
                                                                               
  App\Firefly::createAccount(): Return value must be of type array, stdClass   
  returned
```

I edit the prototype of `createAccount` in [app/Firefly.php](https://github.com/robvankeilegom/firefly-III-paypal-importer/blob/a7177b9c30302986c806c45c44bd3dc527f00878/app/Firefly.php#L188) and remove the return type specification and the import exit without error.

**Comment by robvankeilegom** [comment]
Thanks, i fixed it in master. I'm gonna close this issue. If there's anything else, lmk!
